### ISSUE TITLE
Missing library (rtl250.bpl)

### ISSUE THREAD

**Issue by theNestruo** [Threetwosevensixseven/ayfxedit-improved#1]
The provided .exe doesn't seem to work; the error message says rtl250.bpl is missing.
May be a run-time library ("rtl") from Embarcadero (that should be distributed along the .exe)?

I'm running Windows 10 (version 1803, compilation 17134.228) and it is a relatively clean install.

Thanks!

**Comment by basalicante** [comment]
Same here, Windows 10, rtl250.bpl is missing. Would be great if you could have a look. Cheers!

**Comment by Threetwosevensixseven** [comment]
I haven't got to the bottom of the underlying issue why this happens in some Windows 10 environments but not others.

However I've made a build that should be completely self-contained, which makes a much larger exe.

https://github.com/Threetwosevensixseven/ayfxedit-improved/releases/tag/v0.6-full

Try this and see if it fixes the issue for you.

**Comment by theNestruo** [comment]
Yes, the issue is fixed.
Thank you very much! :)
